---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[python]
      - recipe[git]
      - recipe[rogue::java]
      - recipe[rogue::permissions]
      - recipe[rogue::nginx]
      - recipe[rogue::tomcat]
    attributes: {}