---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      box: ubuntu-12.04
      box_url: "http://files.vagrantup.com/precise64.box"
      customize:
        memory: 5000
        cpus: 10

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[python]
      - recipe[git]
      - recipe[rogue::java]
      - recipe[rogue::permissions]
      - recipe[rogue::nginx]
      - recipe[rogue::tomcat]
    attributes: {}